EnemyName_Glop:	dc.b	"Glop", $FC
EnemyName_Ooze:	dc.b	"Ooze", $FC
EnemyName_Slime:	dc.b	"Slime", $FC
EnemyName_Fire:	dc.b	"Fire", $FC
EnemyName_Murafire:	dc.b	"Murafire", $FC
EnemyName_Azufire:	dc.b	"Azufire", $FC
EnemyName_Nayl:	dc.b	"Nayl", $FC
EnemyName_Flayl:	dc.b	"Flayl", $FC
EnemyName_Slayl:	dc.b	"Slayl", $FC
EnemyName_Dryad:	dc.b	"Dryad", $FC
EnemyName_Nereid:	dc.b	"Nereid", $FC
EnemyName_Sylph:	dc.b	"Sylph", $FC
EnemyName_Buzzgull:	dc.b	"Buzzgull", $FC
EnemyName_Lashgull:	dc.b	"Lashgull", $FC
EnemyName_Hackgull:	dc.b	"Hackgull", $FC
EnemyName_Eindon:	dc.b	"Eindon", $FC
EnemyName_Tsveidon:	dc.b	"Tsveidon", $FC
EnemyName_Dreidon:	dc.b	"Dreidon", $FC
EnemyName_Clump:	dc.b	"Clump", $FC
EnemyName_Cluster:	dc.b	"Cluster", $FC
EnemyName_Clique:	dc.b	"Clique", $FC
EnemyName_Chirper:	dc.b	"Chirper", $FC
EnemyName_Warbler:	dc.b	"Warbler", $FC
EnemyName_Squawker:	dc.b	"Squawker", $FC
EnemyName_Lizrd:	dc.b	"Lizrd", $FC
EnemyName_Blizrd:	dc.b	"Blizrd", $FC
EnemyName_Grizrd:	dc.b	"Grizrd", $FC
EnemyName_Spinner:	dc.b	"Spinner", $FC
EnemyName_Twirler:	dc.b	"Twirler", $FC
EnemyName_Wizzer:	dc.b	"Wizzer", $FC
EnemyName_Imp:	dc.b	"Imp", $FC
EnemyName_Impfoul:	dc.b	"Impfoul", $FC
EnemyName_Impvile:	dc.b	"Impvile", $FC
EnemyName_Nova:	dc.b	"Nova", $FC
EnemyName_Pulsar:	dc.b	"Pulsar", $FC
EnemyName_Quasar:	dc.b	"Quasar", $FC
EnemyName_Chirpbot:	dc.b	"Chirpbot", $FC
EnemyName_Warblbot:	dc.b	"Warblbot", $FC
EnemyName_Squakbot:	dc.b	"Squakbot", $FC
EnemyName_Commsat:	dc.b	"Commsat", $FC
EnemyName_Spysat:	dc.b	"Spysat", $FC
EnemyName_Killsat:	dc.b	"Killsat", $FC
EnemyName_Arachne:	dc.b	"Arachne", $FC
EnemyName_Darachne:	dc.b	"Darachne", $FC
EnemyName_Zarachne:	dc.b	"Zarachne", $FC
EnemyName_Blink:	dc.b	"Blink", $FC
EnemyName_Flash:	dc.b	"Flash", $FC
EnemyName_Strobe:	dc.b	"Strobe", $FC
EnemyName_Minimech:	dc.b	"Minimech", $FC
EnemyName_Mech:	dc.b	"Mech", $FC
EnemyName_Maxmech:	dc.b	"Maxmech", $FC
EnemyName_Lazrbot:	dc.b	"Lazrbot", $FC
EnemyName_Mazrbot:	dc.b	"Mazrbot", $FC
EnemyName_Fazrbot:	dc.b	"Fazrbot", $FC
EnemyName_Emir:	dc.b	"Emir", $FC
EnemyName_Sheik:	dc.b	"Sheik", $FC
EnemyName_Caliph:	dc.b	"Caliph", $FC
EnemyName_Harpy:	dc.b	"Harpy", $FC
EnemyName_Griffin:	dc.b	"Griffin", $FC
EnemyName_Gryphon:	dc.b	"Gryphon", $FC
EnemyName_Banshee:	dc.b	"Banshee", $FC
EnemyName_Ghost:	dc.b	"Ghost", $FC
EnemyName_Haunt:	dc.b	"Haunt", $FC
EnemyName_Beastess:	dc.b	"Beastess", $FC
EnemyName_Trogess:	dc.b	"Trogess", $FC
EnemyName_Demoness:	dc.b	"Demoness", $FC
EnemyName_Bushi:	dc.b	"Bushi", $FC
EnemyName_Kensai:	dc.b	"Kensai", $FC
EnemyName_Samurai:	dc.b	"Samurai", $FC
EnemyName_Irisa:	dc.b	"Irisa", $FC
EnemyName_Rosa:	dc.b	"Rosa", $FC
EnemyName_Viola:	dc.b	"Viola", $FC
EnemyName_Moos:	dc.b	"Moos", $FC
EnemyName_Fearmoos:	dc.b	"Fearmoos", $FC
EnemyName_Diremoos:	dc.b	"Diremoos", $FC
EnemyName_Blueroot:	dc.b	"Blueroot", $FC
EnemyName_Pinkroot:	dc.b	"Pinkroot", $FC
EnemyName_Goldroot:	dc.b	"Goldroot", $FC
EnemyName_Catwoman:	dc.b	"Catwoman", $FC
EnemyName_Tigress:	dc.b	"Tigress", $FC
EnemyName_Lioness:	dc.b	"Lioness", $FC
EnemyName_Lobowing:	dc.b	"Lobowing", $FC
EnemyName_Lobobat:	dc.b	"Lobobat", $FC
EnemyName_Lobohawk:	dc.b	"Lobohawk", $FC
EnemyName_Hopliz:	dc.b	"Hopliz", $FC
EnemyName_Leapliz:	dc.b	"Leapliz", $FC
EnemyName_Jumpliz:	dc.b	"Jumpliz", $FC
EnemyName_Glowtoad:	dc.b	"Glowtoad", $FC
EnemyName_Gilatoad:	dc.b	"Gilatoad", $FC
EnemyName_Megatoad:	dc.b	"Megatoad", $FC
EnemyName_Seeker:	dc.b	"Seeker", $FC
EnemyName_Hunter:	dc.b	"Hunter", $FC
EnemyName_Killer:	dc.b	"Killer", $FC
EnemyName_Roboman:	dc.b	"Roboman", $FC
EnemyName_Mechman:	dc.b	"Mechman", $FC
EnemyName_Droidman:	dc.b	"Droidman", $FC
EnemyName_Fatale:	dc.b	"Fatale", $FC
EnemyName_Morte:	dc.b	"Morte", $FC
EnemyName_Finis:	dc.b	"Finis", $FC
EnemyName_Stickle:	dc.b	"Stickle", $FC
EnemyName_Twig:	dc.b	"Twig", $FC
EnemyName_Mantis:	dc.b	"Mantis", $FC
EnemyName_Stix:	dc.b	"Stix", $FC
EnemyName_Glazstix:	dc.b	"Glazstix", $FC
EnemyName_Metlstix:	dc.b	"Metlstix", $FC
EnemyName_Twistbot:	dc.b	"Twistbot", $FC
EnemyName_Swivlbot:	dc.b	"Swivlbot", $FC
EnemyName_Rotabot:	dc.b	"Rotabot", $FC
EnemyName_Orb:	dc.b	"Orb", $FC
EnemyName_Globe:	dc.b	"Globe", $FC
EnemyName_Sphere:	dc.b	"Sphere", $FC
EnemyName_Drake:	dc.b	"Drake", $FC
EnemyName_Dragon:	dc.b	"Dragon", $FC
EnemyName_Wyrm:	dc.b	"Wyrm", $FC
EnemyName_Skeleton:	dc.b	"Skeleton", $FC
EnemyName_Spectre:	dc.b	"Spectre", $FC
EnemyName_Wraith:	dc.b	"Wraith", $FC
EnemyName_Grinder:	dc.b	"Grinder", $FC
EnemyName_Smasher:	dc.b	"Smasher", $FC
EnemyName_Crusher:	dc.b	"Crusher", $FC
EnemyName_Clops:	dc.b	"Clops", $FC
EnemyName_Biclops:	dc.b	"Biclops", $FC
EnemyName_Triclops:	dc.b	"Triclops", $FC
EnemyName_Dogbot:	dc.b	"Dogbot", $FC
EnemyName_Feralbot:	dc.b	"Feralbot", $FC
EnemyName_Wolfbot:	dc.b	"Wolfbot", $FC
EnemyName_Amazon:	dc.b	"Amazon", $FC
EnemyName_Erinye:	dc.b	"Erinye", $FC
EnemyName_Valkyrie:	dc.b	"Valkyrie", $FC
EnemyName_Giant:	dc.b	"Giant", $FC
EnemyName_Titan:	dc.b	"Titan", $FC
EnemyName_Colossus:	dc.b	"Colossus", $FC
EnemyName_Primus:	dc.b	"Primus", $FC
EnemyName_Secundus:	dc.b	"Secundus", $FC
EnemyName_Tertius:	dc.b	"Tertius", $FC
EnemyName_Lasher:	dc.b	"Lasher", $FC
EnemyName_Slasher:	dc.b	"Slasher", $FC
EnemyName_Gnasher:	dc.b	"Gnasher", $FC
EnemyName_Doomfly:	dc.b	"Doomfly", $FC
EnemyName_Demonfly:	dc.b	"Demonfly", $FC
EnemyName_Deathfly:	dc.b	"Deathfly", $FC
EnemyName_Blotter:	dc.b	"Blotter", $FC
EnemyName_Flutter:	dc.b	"Flutter", $FC
EnemyName_Splatter:	dc.b	"Splatter", $FC
EnemyName_Polebot:	dc.b	"Polebot", $FC
EnemyName_Stickbot:	dc.b	"Stickbot", $FC
EnemyName_Wirebot:	dc.b	"Wirebot", $FC
EnemyName_Agribot:	dc.b	"Agribot", $FC
EnemyName_Guardbot:	dc.b	"Guardbot", $FC
EnemyName_Warbot:	dc.b	"Warbot", $FC
EnemyName_Flopper:	dc.b	"Flopper", $FC
EnemyName_Disker:	dc.b	"Disker", $FC
EnemyName_Carder:	dc.b	"Carder", $FC
EnemyName_Punisher:	dc.b	"Punisher", $FC
EnemyName_Torturer:	dc.b	"Torturer", $FC
EnemyName_Executer:	dc.b	"Executer", $FC
EnemyName_Fatima:	dc.b	"Fatima", $FC
EnemyName_Zafirah:	dc.b	"Zafirah", $FC
EnemyName_Khalidah:	dc.b	"Khalidah", $FC
EnemyName_Watcher:	dc.b	"Watcher", $FC
EnemyName_Defender:	dc.b	"Defender", $FC
EnemyName_Guardian:	dc.b	"Guardian", $FC
EnemyName_Dire:	dc.b	"Dire", $FC
EnemyName_Baneful:	dc.b	"Baneful", $FC
EnemyName_Malific:	dc.b	"Malific", $FC
EnemyName_Conjurer:	dc.b	"Conjurer", $FC
EnemyName_Wizard:	dc.b	"Wizard", $FC
EnemyName_Sorcerer:	dc.b	"Sorcerer", $FC
EnemyName_Goatman:	dc.b	"Goatman", $FC
EnemyName_Goatduke:	dc.b	"Goatduke", $FC
EnemyName_Goatking:	dc.b	"Goatking", $FC
EnemyName_Lyle:	dc.b	"Lyle", $FC
EnemyName_Sari:	dc.b	"Sari", $FC
EnemyName_Lune:	dc.b	"Lune", $FC
EnemyName_Kara:	dc.b	"Kara", $FC
EnemyName_Siren:	dc.b	"Siren", $FC
EnemyName_Rulakir:	dc.b	"Rulakir", $FC
EnemyName_KingCille:	dc.b	"King Cille", $FC
EnemyName_RightHand:	dc.b	"RightHand", $FC
EnemyName_LeftHand:	dc.b	"Left Hand", $FC
EnemyName_Body:	dc.b	"Body", $FC