
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'mainALIGN CLEAR COMMENT CURRENT_EVENT END EVEN EVENT FILE SPECIFIC_EVENT START TEXTmain : empty\n                | main scriptscript : FILEempty : '
    
_lr_action_items = {'FILE':([0,1,2,3,4,],[-4,4,-1,-2,-3,]),'$end':([0,1,2,3,4,],[-4,0,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'main':([0,],[1,]),'empty':([0,],[2,]),'script':([1,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> main","S'",1,None,None,None),
  ('main -> empty','main',1,'p_main','script_parser.py',108),
  ('main -> main script','main',2,'p_main','script_parser.py',109),
  ('script -> FILE','script',1,'p_script','script_parser.py',119),
  ('empty -> <empty>','empty',0,'p_empty','script_parser.py',123),
]
